[package]
name = "rusted_cypher"
version = "1.1.1"
authors = ["Kevin Brendle <khbrendle93@gmail.com>"]
description = "Send cypher queries to a neo4j database"
repository = "https://github.com/khbrendle/rusted-cypher"
documentation = "https://docs.rs/rusted_cypher/"
readme = "README.md"
categories = ["database"]
keywords = ["neo4j", "database", "rest", "cypher", "graph"]
license = "MIT/Apache-2.0"
include = [
  "src/**/*",
  "build.rs",
  "Cargo.toml",
  "LICENSE-*",
  "README.md",
  "CHANGELOG.md",
]

[dependencies]
hyper = "0.10"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
semver = "0.5"
time = "0.1"
quick-error = "1.1"
log = "0.3"
